/*****************************************************************************
 * THIS FILE IS AUTOMATICALLY GENERATED. ANY CHANGES TO THIS FILE
 * WILL BE LOST IN NEXT BUILD. CHANGES SHOULD BE MADE IN FILE
 * SVN_VERS.BAT
 *****************************************************************************/
/*****************************************************************************
 *	\file		version.h
 *
 *	\date		2013-May-27
 *
 *	\brief		Version info for Limes Audio True Voice module
 *
 *	Copyright	Limes Audio AB
 *
 *	This code should not be modified, copied, duplicated, reproduced, licensed
 *	or sublicensed without the prior written consent of Limes Audio AB.
 *	This code, or any right in the code, should not be transferred or conveyed
 *	without the prior written consent of Limes Audio AB.
 *
 *****************************************************************************/
#ifndef TV_VERSION_H
#define TV_VERSION_H

// Major version number
#define TV_VERSION_MAJOR	0
// Minor version number
#define TV_VERSION_MINOR	1
// This is the SVN version number for latest commit for all files in this
// folder. The placeholder is updated in a pre-build step by the batch
// file "svn_vers.bat".
#define TV_VERSION_BUILD	261

#endif // TV_VERSION_H
